# Generated by Django 3.0.2 on 2020-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
